ClassBlast-admin/grails-app/domain/classblast/admin/Cuaderno.groovy
package classblast.admin


class Cuaderno {
	String bookName
	Semestre semesterRelated
	Curso courseRelated
	User bookOwner
	static hasMany = [sectionList:Seccion]
	static constraints = {
	}
}

ClassBlast-admin/grails-app/controllers/classblast/admin/CuadernoController.groovy
package classblast.admin



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CuadernoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Cuaderno.list(params), model:[cuadernoInstanceCount: Cuaderno.count()]
    }

    def show(Cuaderno cuadernoInstance) {
        respond cuadernoInstance
    }

    def create() {
        respond new Cuaderno(params)
    }

    @Transactional
    def save(Cuaderno cuadernoInstance) {
        if (cuadernoInstance == null) {
            notFound()
            return
        }

        if (cuadernoInstance.hasErrors()) {
            respond cuadernoInstance.errors, view:'create'
            return
        }

        cuadernoInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'cuadernoInstance.label', default: 'Cuaderno'), cuadernoInstance.id])
                redirect cuadernoInstance
            }
            '*' { respond cuadernoInstance, [status: CREATED] }
        }
    }

    def edit(Cuaderno cuadernoInstance) {
        respond cuadernoInstance
    }

    @Transactional
    def update(Cuaderno cuadernoInstance) {
        if (cuadernoInstance == null) {
            notFound()
            return
        }

        if (cuadernoInstance.hasErrors()) {
            respond cuadernoInstance.errors, view:'edit'
            return
        }

        cuadernoInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Cuaderno.label', default: 'Cuaderno'), cuadernoInstance.id])
                redirect cuadernoInstance
            }
            '*'{ respond cuadernoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Cuaderno cuadernoInstance) {

        if (cuadernoInstance == null) {
            notFound()
            return
        }

        cuadernoInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Cuaderno.label', default: 'Cuaderno'), cuadernoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'cuadernoInstance.label', default: 'Cuaderno'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

ClassBlast-admin/grails-app/views/cuaderno/_form.gsp
<%@ page import="classblast.admin.Cuaderno" %>



<div class="fieldcontain ${hasErrors(bean: cuadernoInstance, field: 'bookName', 'error')} ">
	<label for="bookName">
		<g:message code="cuaderno.bookName.label" default="Book Name" />
		
	</label>
	<g:textField name="bookName" value="${cuadernoInstance?.bookName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: cuadernoInstance, field: 'bookOwner', 'error')} required">
	<label for="bookOwner">
		<g:message code="cuaderno.bookOwner.label" default="Book Owner" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="bookOwner" name="bookOwner.id" from="${classblast.admin.User.list()}" optionKey="id" required="" value="${cuadernoInstance?.bookOwner?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: cuadernoInstance, field: 'courseRelated', 'error')} required">
	<label for="courseRelated">
		<g:message code="cuaderno.courseRelated.label" default="Course Related" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="courseRelated" name="courseRelated.id" from="${classblast.admin.Curso.list()}" optionKey="id" required="" value="${cuadernoInstance?.courseRelated?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: cuadernoInstance, field: 'sectionList', 'error')} ">
	<label for="sectionList">
		<g:message code="cuaderno.sectionList.label" default="Section List" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${cuadernoInstance?.sectionList?}" var="s">
    <li><g:link controller="seccion" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="seccion" action="create" params="['cuaderno.id': cuadernoInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'seccion.label', default: 'Seccion')])}</g:link>
</li>
</ul>

</div>

<div class="fieldcontain ${hasErrors(bean: cuadernoInstance, field: 'semesterRelated', 'error')} required">
	<label for="semesterRelated">
		<g:message code="cuaderno.semesterRelated.label" default="Semester Related" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="semesterRelated" name="semesterRelated.id" from="${classblast.admin.Semestre.list()}" optionKey="id" required="" value="${cuadernoInstance?.semesterRelated?.id}" class="many-to-one"/>
</div>

ClassBlast-admin/grails-app/views/cuaderno/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cuaderno.label', default: 'Cuaderno')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-cuaderno" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-cuaderno" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cuadernoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cuadernoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:cuadernoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

ClassBlast-admin/grails-app/views/cuaderno/edit.gsp
<%@ page import="classblast.admin.Cuaderno" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cuaderno.label', default: 'Cuaderno')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-cuaderno" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-cuaderno" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cuadernoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cuadernoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:cuadernoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${cuadernoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

ClassBlast-admin/grails-app/views/cuaderno/index.gsp
<%@ page import="classblast.admin.Cuaderno" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cuaderno.label', default: 'Cuaderno')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-cuaderno" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-cuaderno" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="bookName" title="${message(code: 'cuaderno.bookName.label', default: 'Book Name')}" />
					
						<th><g:message code="cuaderno.bookOwner.label" default="Book Owner" /></th>
					
						<th><g:message code="cuaderno.courseRelated.label" default="Course Related" /></th>
					
						<th><g:message code="cuaderno.semesterRelated.label" default="Semester Related" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${cuadernoInstanceList}" status="i" var="cuadernoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${cuadernoInstance.id}">${fieldValue(bean: cuadernoInstance, field: "bookName")}</g:link></td>
					
						<td>${fieldValue(bean: cuadernoInstance, field: "bookOwner")}</td>
					
						<td>${fieldValue(bean: cuadernoInstance, field: "courseRelated")}</td>
					
						<td>${fieldValue(bean: cuadernoInstance, field: "semesterRelated")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${cuadernoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

ClassBlast-admin/grails-app/views/cuaderno/show.gsp
<%@ page import="classblast.admin.Cuaderno" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cuaderno.label', default: 'Cuaderno')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-cuaderno" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-cuaderno" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list cuaderno">
			
				<g:if test="${cuadernoInstance?.bookName}">
				<li class="fieldcontain">
					<span id="bookName-label" class="property-label"><g:message code="cuaderno.bookName.label" default="Book Name" /></span>
					
						<span class="property-value" aria-labelledby="bookName-label"><g:fieldValue bean="${cuadernoInstance}" field="bookName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${cuadernoInstance?.bookOwner}">
				<li class="fieldcontain">
					<span id="bookOwner-label" class="property-label"><g:message code="cuaderno.bookOwner.label" default="Book Owner" /></span>
					
						<span class="property-value" aria-labelledby="bookOwner-label"><g:link controller="user" action="show" id="${cuadernoInstance?.bookOwner?.id}">${cuadernoInstance?.bookOwner?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${cuadernoInstance?.courseRelated}">
				<li class="fieldcontain">
					<span id="courseRelated-label" class="property-label"><g:message code="cuaderno.courseRelated.label" default="Course Related" /></span>
					
						<span class="property-value" aria-labelledby="courseRelated-label"><g:link controller="curso" action="show" id="${cuadernoInstance?.courseRelated?.id}">${cuadernoInstance?.courseRelated?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${cuadernoInstance?.sectionList}">
				<li class="fieldcontain">
					<span id="sectionList-label" class="property-label"><g:message code="cuaderno.sectionList.label" default="Section List" /></span>
					
						<g:each in="${cuadernoInstance.sectionList}" var="s">
						<span class="property-value" aria-labelledby="sectionList-label"><g:link controller="seccion" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${cuadernoInstance?.semesterRelated}">
				<li class="fieldcontain">
					<span id="semesterRelated-label" class="property-label"><g:message code="cuaderno.semesterRelated.label" default="Semester Related" /></span>
					
						<span class="property-value" aria-labelledby="semesterRelated-label"><g:link controller="semestre" action="show" id="${cuadernoInstance?.semesterRelated?.id}">${cuadernoInstance?.semesterRelated?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:cuadernoInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${cuadernoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>