ClassBlast-admin/grails-app/domain/classblast/admin/Mensaje.groovy
package classblast.admin

import java.util.Date;

class Mensaje {
	User ownerMessage
	Date dateMessage
	Conversacion conversation
    static constraints = {
    }
}

ClassBlast-admin/grails-app/controllers/classblast/admin/MensajeController.groovy
package classblast.admin



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class MensajeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Mensaje.list(params), model:[mensajeInstanceCount: Mensaje.count()]
    }

    def show(Mensaje mensajeInstance) {
        respond mensajeInstance
    }

    def create() {
        respond new Mensaje(params)
    }

    @Transactional
    def save(Mensaje mensajeInstance) {
        if (mensajeInstance == null) {
            notFound()
            return
        }

        if (mensajeInstance.hasErrors()) {
            respond mensajeInstance.errors, view:'create'
            return
        }

        mensajeInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'mensajeInstance.label', default: 'Mensaje'), mensajeInstance.id])
                redirect mensajeInstance
            }
            '*' { respond mensajeInstance, [status: CREATED] }
        }
    }

    def edit(Mensaje mensajeInstance) {
        respond mensajeInstance
    }

    @Transactional
    def update(Mensaje mensajeInstance) {
        if (mensajeInstance == null) {
            notFound()
            return
        }

        if (mensajeInstance.hasErrors()) {
            respond mensajeInstance.errors, view:'edit'
            return
        }

        mensajeInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Mensaje.label', default: 'Mensaje'), mensajeInstance.id])
                redirect mensajeInstance
            }
            '*'{ respond mensajeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Mensaje mensajeInstance) {

        if (mensajeInstance == null) {
            notFound()
            return
        }

        mensajeInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Mensaje.label', default: 'Mensaje'), mensajeInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'mensajeInstance.label', default: 'Mensaje'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

ClassBlast-admin/grails-app/views/mensaje/_form.gsp
<%@ page import="classblast.admin.Mensaje" %>



<div class="fieldcontain ${hasErrors(bean: mensajeInstance, field: 'conversation', 'error')} required">
	<label for="conversation">
		<g:message code="mensaje.conversation.label" default="Conversation" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="conversation" name="conversation.id" from="${classblast.admin.Conversacion.list()}" optionKey="id" required="" value="${mensajeInstance?.conversation?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: mensajeInstance, field: 'dateMessage', 'error')} required">
	<label for="dateMessage">
		<g:message code="mensaje.dateMessage.label" default="Date Message" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="dateMessage" precision="day"  value="${mensajeInstance?.dateMessage}"  />
</div>

<div class="fieldcontain ${hasErrors(bean: mensajeInstance, field: 'ownerMessage', 'error')} required">
	<label for="ownerMessage">
		<g:message code="mensaje.ownerMessage.label" default="Owner Message" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="ownerMessage" name="ownerMessage.id" from="${classblast.admin.User.list()}" optionKey="id" required="" value="${mensajeInstance?.ownerMessage?.id}" class="many-to-one"/>
</div>

ClassBlast-admin/grails-app/views/mensaje/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mensaje.label', default: 'Mensaje')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-mensaje" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-mensaje" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${mensajeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${mensajeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:mensajeInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

ClassBlast-admin/grails-app/views/mensaje/edit.gsp
<%@ page import="classblast.admin.Mensaje" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mensaje.label', default: 'Mensaje')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-mensaje" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-mensaje" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${mensajeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${mensajeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:mensajeInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${mensajeInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

ClassBlast-admin/grails-app/views/mensaje/index.gsp
<%@ page import="classblast.admin.Mensaje" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mensaje.label', default: 'Mensaje')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-mensaje" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-mensaje" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="mensaje.conversation.label" default="Conversation" /></th>
					
						<g:sortableColumn property="dateMessage" title="${message(code: 'mensaje.dateMessage.label', default: 'Date Message')}" />
					
						<th><g:message code="mensaje.ownerMessage.label" default="Owner Message" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${mensajeInstanceList}" status="i" var="mensajeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${mensajeInstance.id}">${fieldValue(bean: mensajeInstance, field: "conversation")}</g:link></td>
					
						<td><g:formatDate date="${mensajeInstance.dateMessage}" /></td>
					
						<td>${fieldValue(bean: mensajeInstance, field: "ownerMessage")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${mensajeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

ClassBlast-admin/grails-app/views/mensaje/show.gsp
<%@ page import="classblast.admin.Mensaje" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mensaje.label', default: 'Mensaje')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-mensaje" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-mensaje" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list mensaje">
			
				<g:if test="${mensajeInstance?.conversation}">
				<li class="fieldcontain">
					<span id="conversation-label" class="property-label"><g:message code="mensaje.conversation.label" default="Conversation" /></span>
					
						<span class="property-value" aria-labelledby="conversation-label"><g:link controller="conversacion" action="show" id="${mensajeInstance?.conversation?.id}">${mensajeInstance?.conversation?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${mensajeInstance?.dateMessage}">
				<li class="fieldcontain">
					<span id="dateMessage-label" class="property-label"><g:message code="mensaje.dateMessage.label" default="Date Message" /></span>
					
						<span class="property-value" aria-labelledby="dateMessage-label"><g:formatDate date="${mensajeInstance?.dateMessage}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${mensajeInstance?.ownerMessage}">
				<li class="fieldcontain">
					<span id="ownerMessage-label" class="property-label"><g:message code="mensaje.ownerMessage.label" default="Owner Message" /></span>
					
						<span class="property-value" aria-labelledby="ownerMessage-label"><g:link controller="user" action="show" id="${mensajeInstance?.ownerMessage?.id}">${mensajeInstance?.ownerMessage?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:mensajeInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${mensajeInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>